development:
  adapter: postgresql
  encoding: utf8
  database: appdroneapp_development
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: appdroneapp_test
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: appdroneapp_production
  username:
  password:
